---
title: "Amazon sales"
subtitle: "Sales report"
author: "Sean Ng"
organization: "AIMdata"
date: '`r format(Sys.Date())`'
output: html_document
params: 
  dataset: NULL
execute: 
  echo: false
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 9)


library(tidyverse)
library(janitor)
library(scales)
library(patchwork)
library(viridis)
library(stringr)
library(sf)
library(broom)
library(ggh4x)

`%out%` <- Negate(`%in%`)
options(scipen = 100)
theme_set(theme_light())
range_wna <- function(x){(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))}

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

last_comma <- function(x, sep = ","){
  x <- sapply(strsplit(x, sep),"[")
  trimws(x[[length(x)]])
}
```

Fx rates come from here[https://www.exchangerates.org.uk/USD-INR-spot-exchange-rates-history-2023.html], average rate for 2023

```{r}
# This is the way to run it

usd_to_inr <- 82.5738

amazon <- params$dataset |>  
  rename(discounted_price_inr = discounted_price, 
         actual_price_inr = actual_price) |> 
  mutate_at(
    vars(discounted_price_inr, 
         actual_price_inr), 
    ~ as.numeric(
      str_remove(str_remove(., "₹"), ",")
      )
  ) |> 
  mutate(discounted_price = discounted_price_inr / usd_to_inr, 
         actual_price = actual_price_inr / usd_to_inr) |> 
  mutate(discount_percentage = 
           as.numeric(str_remove(discount_percentage, "%")), 
         discount_percentage = discount_percentage / 100)

categories <- amazon |> 
  distinct(product_id, category) |> 
  mutate(final_category = str_extract(category, "[^|]+$"), 
         first_category = str_extract(category, "^[^|]+")) |> 
  mutate(second_category = str_split_i(category, "\\|", 2)) |> 
  select(product_id, first_category, second_category, final_category)
```


```{r}
amazon |> 
  ggplot(aes(x = rating_count)) + 
  geom_histogram() + 
  scale_x_log10()
```


```{r warning=FALSE, fig.height=8}

backgrounds <- 
  list(
    element_rect(fill = "#780000"), 
    element_rect(fill = "#780000"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#780000"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#606c38"),
    element_rect(fill = "#003049"),
    element_rect(fill = "#669bbc"),
    element_rect(fill = "#780000"),
    element_rect(fill = "#780000"),
    element_rect(fill = "#003049"),
    element_rect(fill = "#003049"),
    element_rect(fill = "#003049")
  )

amazon |> 
    left_join(
      categories,
      by = "product_id"
    ) |> 
  filter(!is.na(rating_count)) |> 
  group_by(first_category, second_category, rating, discounted_price) |>
  summarise(rating_count = mean(rating_count), 
            .groups = "drop") |> 
  filter(second_category %in% c("Accessories", "Accessories&Peripherals", 
                              "Cameras&Photography", "Components", 
                              "CraftMaterials",
                              "ExternalDevices&DataStorage", 
                              "GeneralPurposeBatteries&BatteryChargers", 
                              "Headphones,Earbuds&Accessories",
                              "Heating,Cooling&AirQuality", 
                              "HomeAudio", "HomeStorage&Organization", 
                              "HomeTheater,TV&Video", 
                              "Kitchen&HomeAppliances", 
                              "Mobiles&Accessories", 
                              "NetworkingDevices", "OfficePaperProducts", 
                              "Printers,Inks&Accessories", 
                              "WearableTechnology")) |> 
  ggplot(aes(x = discounted_price, y = rating)) + 
  geom_point() + 
  geom_smooth() + 
  facet_wrap2(vars(second_category), 
              scales = "free", 
              strip = strip_themed(
               background_x = backgrounds)) + 
  scale_x_log10() + 
  labs(title = "Amazon product ratings and prices", 
       subtitle = "Categories are: Computers & Accessories; Electronics; Office products; and Home & Kitchen")
```
